In [1]:
import requests
import matplotlib.pyplot as plt
import json
import pandas as pd

## #1)

In [2]:
endpoint = 'https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD'

params = {
    'format': 'json',
    'per_page': 17024
}

response = requests.get(endpoint, params = params)

In [3]:
response

In [4]:
res = response.json()

In [5]:
pd.DataFrame(res[1])['indicator'][0]

gdp_ppp = pd.json_normalize(res[1])

In [6]:
gdp_ppp['indicator.value'].reset_index()

       index                                    indicator.value
0          0  GDP per capita, PPP (constant 2021 internation...
1          1  GDP per capita, PPP (constant 2021 internation...
2          2  GDP per capita, PPP (constant 2021 internation...
3          3  GDP per capita, PPP (constant 2021 internation...
4          4  GDP per capita, PPP (constant 2021 internation...
...      ...                                                ...
17019  17019  GDP per capita, PPP (constant 2021 internation...
17020  17020  GDP per capita, PPP (constant 2021 internation...
17021  17021  GDP per capita, PPP (constant 2021 internation...
17022  17022  GDP per capita, PPP (constant 2021 internation...
17023  17023  GDP per capita, PPP (constant 2021 internation...

[17024 rows x 2 columns]

In [7]:
gdp_ppp

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,AFE,2023,4047.007031,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
1,AFE,2022,4038.638689,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
2,AFE,2021,3994.171654,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
3,AFE,2020,3919.499230,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
4,AFE,2019,4130.057222,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
...,...,...,...,...,...,...,...,...,...,...
17019,ZWE,1964,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZW,Zimbabwe
17020,ZWE,1963,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZW,Zimbabwe
17021,ZWE,1962,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZW,Zimbabwe
17022,ZWE,1961,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZW,Zimbabwe
17023,ZWE,1960,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZW,Zimbabwe

In [8]:

gdp_ppp.shape
#gdp_ppp['indicator'][]

(17024, 10)

## #2)

In [9]:
endpoint = 'https://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN'

params = {
    'format': 'json',
    'per_page': 17024
}

response = requests.get(endpoint, params = params)

In [10]:
response

In [11]:
res2 = response.json()

In [12]:
res2[1]

[{'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2023',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2022',
  'value': 62.8990306485382,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2021',
  'value': 62.4545896453863,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2020',
  'value': 63.313860330682,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2019',
  'value': 63.7556779176533,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2018',
  'value': 63.3658626111831,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2017',
  'value': 62.9223896233502,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2016',
  'value': 62.444050201953,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2015',
  'value': 61.8564581403595,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2014',
  'value': 61.3379174832409,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2013',
  'value': 60.7098695610582,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2012',
  'value': 60.0507802468673,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2011',
  'value': 59.2932713889337,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2010',
  'value': 58.4111497501441,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2009',
  'value': 57.6208515442432,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2008',
  'value': 56.6804188973962,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2007',
  'value': 55.9338017149142,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2006',
  'value': 55.1505461100496,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2005',
  'value': 54.2196508058582,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2004',
  'value': 53.5454571098034,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2003',
  'value': 53.0220345898659,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2002',
  'value': 52.540794004192,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2001',
  'value': 52.189648214333,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2000',
  'value': 51.9644813247726,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1999',
  'value': 51.2378519083819,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1998',
  'value': 50.3259127442221,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1997',
  'value': 50.9742313589474,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1996',
  'value': 50.8106889705148,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1995',
  'value': 51.0019252899341,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1994',
  'value': 50.882581820857,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1993',
  'value': 50.2736279712378,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1992',
  'value': 49.9621136475362,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1991',
  'value': 50.3904596093263,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1990',
  'value': 50.6077275337211,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1989',
  'value': 50.6840997852884,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1988',
  'value': 49.3597265265243,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1987',
  'value': 50.0758875408274,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1986',
  'value': 49.6397190079537,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1985',
  'value': 49.0116307202704,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1984',
  'value': 48.6526645552392,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1983',
  'value': 48.7033305923076,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1982',
  'value': 50.2968491379812,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1981',
  'value': 50.0570732913929,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1980',
  'value': 49.6365376633939,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1979',
  'value': 49.261335737194,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1978',
  'value': 48.7636045995518,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1977',
  'value': 48.6359051941044,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1976',
  'value': 48.3495880515137,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1975',
  'value': 47.7598869102852,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1974',
  'value': 47.5980637543936,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1973',
  'value': 47.6923174333565,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1972',
  'value': 46.8973892484582,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1971',
  'value': 47.1929422628056,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1970',
  'value': 46.7184845197579,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1969',
  'value': 46.4323030920124,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1968',
  'value': 46.2230965735857,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1967',
  'value': 45.9249050028634,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1966',
  'value': 45.249104629175,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1965',
  'value': 45.4983377851245,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1964',
  'value': 45.4790430350926,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1963',
  'value': 44.9131593023895,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1962',
  'value': 44.7521818697994,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1961',
  'value': 44.386696928982,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1960',
  'value': 44.0855518454965,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2023',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2022',
  'value': 57.626176164197,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2021',
  'value': 56.9886567820139,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2020',
  'value': 57.2263727312399,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2019',
  'value': 57.5557955517512,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.DYN.LE00.IN',
   'value': 'Life expectancy at birth, total (years)'},

In [13]:
pd.DataFrame(res2[1])

LifeExp_TotYears = pd.json_normalize(res2[1])

In [14]:
gdp_ppp = gdp_ppp.drop(['indicator.id','indicator.value','decimal','unit','obs_status'], axis = 1)

In [15]:
gdp_ppp.rename(columns = {'value':'GDP_Per_Capita','date':'Year'}, inplace = True)

In [16]:
gdp_ppp

,countryiso3code,Year,GDP_Per_Capita,country.id,country.value
0,AFE,2023,4047.007031,ZH,Africa Eastern and Southern
1,AFE,2022,4038.638689,ZH,Africa Eastern and Southern
2,AFE,2021,3994.171654,ZH,Africa Eastern and Southern
3,AFE,2020,3919.499230,ZH,Africa Eastern and Southern
4,AFE,2019,4130.057222,ZH,Africa Eastern and Southern
...,...,...,...,...,...
17019,ZWE,1964,NaN,ZW,Zimbabwe
17020,ZWE,1963,NaN,ZW,Zimbabwe
17021,ZWE,1962,NaN,ZW,Zimbabwe
17022,ZWE,1961,NaN,ZW,Zimbabwe
17023,ZWE,1960,NaN,ZW,Zimbabwe

In [17]:
LifeExp_TotYears

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,AFE,2023,NaN,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
1,AFE,2022,62.899031,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
2,AFE,2021,62.454590,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
3,AFE,2020,63.313860,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
4,AFE,2019,63.755678,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
...,...,...,...,...,...,...,...,...,...,...
17019,ZWE,1964,54.994000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
17020,ZWE,1963,54.549000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
17021,ZWE,1962,54.071000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
17022,ZWE,1961,53.619000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
17023,ZWE,1960,53.235000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe

In [18]:
LifeExp_TotYears = LifeExp_TotYears.drop(['unit','obs_status','decimal','indicator.id','indicator.value'], axis = 1)
LifeExp_TotYears.rename(columns = {'value':'Life_Exp','date':'Year'}, inplace = True)

In [19]:
gdp_ppp

,countryiso3code,Year,GDP_Per_Capita,country.id,country.value
0,AFE,2023,4047.007031,ZH,Africa Eastern and Southern
1,AFE,2022,4038.638689,ZH,Africa Eastern and Southern
2,AFE,2021,3994.171654,ZH,Africa Eastern and Southern
3,AFE,2020,3919.499230,ZH,Africa Eastern and Southern
4,AFE,2019,4130.057222,ZH,Africa Eastern and Southern
...,...,...,...,...,...
17019,ZWE,1964,NaN,ZW,Zimbabwe
17020,ZWE,1963,NaN,ZW,Zimbabwe
17021,ZWE,1962,NaN,ZW,Zimbabwe
17022,ZWE,1961,NaN,ZW,Zimbabwe
17023,ZWE,1960,NaN,ZW,Zimbabwe

In [20]:
LifeExp_TotYears

      countryiso3code  Year   Life_Exp country.id                country.value
0                 AFE  2023        NaN         ZH  Africa Eastern and Southern
1                 AFE  2022  62.899031         ZH  Africa Eastern and Southern
2                 AFE  2021  62.454590         ZH  Africa Eastern and Southern
3                 AFE  2020  63.313860         ZH  Africa Eastern and Southern
4                 AFE  2019  63.755678         ZH  Africa Eastern and Southern
...               ...   ...        ...        ...                          ...
17019             ZWE  1964  54.994000         ZW                     Zimbabwe
17020             ZWE  1963  54.549000         ZW                     Zimbabwe
17021             ZWE  1962  54.071000         ZW                     Zimbabwe
17022             ZWE  1961  53.619000         ZW                     Zimbabwe
17023             ZWE  1960  53.235000         ZW                     Zimbabwe

[17024 rows x 5 columns]

## #3)

In [21]:
gdp_merged = pd.merge(
    left = gdp_ppp, 
    right = LifeExp_TotYears, 

    indicator = True
)
gdp_merged

,countryiso3code,Year,GDP_Per_Capita,country.id,country.value,Life_Exp,_merge
0,AFE,2023,4047.007031,ZH,Africa Eastern and Southern,NaN,both
1,AFE,2022,4038.638689,ZH,Africa Eastern and Southern,62.899031,both
2,AFE,2021,3994.171654,ZH,Africa Eastern and Southern,62.454590,both
3,AFE,2020,3919.499230,ZH,Africa Eastern and Southern,63.313860,both
4,AFE,2019,4130.057222,ZH,Africa Eastern and Southern,63.755678,both
...,...,...,...,...,...,...,...
17019,ZWE,1964,NaN,ZW,Zimbabwe,54.994000,both
17020,ZWE,1963,NaN,ZW,Zimbabwe,54.549000,both
17021,ZWE,1962,NaN,ZW,Zimbabwe,54.071000,both
17022,ZWE,1961,NaN,ZW,Zimbabwe,53.619000,both
17023,ZWE,1960,NaN,ZW,Zimbabwe,53.235000,both

## #4)

In [22]:
endpoint = 'https://api.worldbank.org/v2/country'

params = {
    'format': 'json',
    'per_page': 296
}

response = requests.get(endpoint, params = params)

In [23]:
response

In [24]:
res3 = response.json()

In [25]:
len(res3)

2

In [26]:
len(res3[1])
res3[1]

[{'id': 'ABW',
  'iso2Code': 'AW',
  'name': 'Aruba',
  'region': {'id': 'LCN',
   'iso2code': 'ZJ',
   'value': 'Latin America & Caribbean '},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Oranjestad',
  'longitude': '-70.0167',
  'latitude': '12.5167'},
 {'id': 'AFE',
  'iso2Code': 'ZH',
  'name': 'Africa Eastern and Southern',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'AFG',
  'iso2Code': 'AF',
  'name': 'Afghanistan',
  'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
  'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
  'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'},
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'capitalCity': 'Kabul',
  'longitude': '69.1761',
  'latitude': '34.5228'},
 {'id': 'AFR',
  'iso2Code': 'A9',
  'name': 'Africa',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'AFW',
  'iso2Code': 'ZI',
  'name': 'Africa Western and Central',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'AGO',
  'iso2Code': 'AO',
  'name': 'Angola',
  'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
  'adminregion': {'id': 'SSA',
   'iso2code': 'ZF',
   'value': 'Sub-Saharan Africa (excluding high income)'},
  'incomeLevel': {'id': 'LMC',
   'iso2code': 'XN',
   'value': 'Lower middle income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'Luanda',
  'longitude': '13.242',
  'latitude': '-8.81155'},
 {'id': 'ALB',
  'iso2Code': 'AL',
  'name': 'Albania',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
  'adminregion': {'id': 'ECA',
   'iso2code': '7E',
   'value': 'Europe & Central Asia (excluding high income)'},
  'incomeLevel': {'id': 'UMC',
   'iso2code': 'XT',
   'value': 'Upper middle income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'Tirane',
  'longitude': '19.8172',
  'latitude': '41.3317'},
 {'id': 'AND',
  'iso2Code': 'AD',
  'name': 'Andorra',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Andorra la Vella',
  'longitude': '1.5218',
  'latitude': '42.5075'},
 {'id': 'ARB',
  'iso2Code': '1A',
  'name': 'Arab World',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'ARE',
  'iso2Code': 'AE',
  'name': 'United Arab Emirates',
  'region': {'id': 'MEA',
   'iso2code': 'ZQ',
   'value': 'Middle East & North Africa'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Abu Dhabi',
  'longitude': '54.3705',
  'latitude': '24.4764'},
 {'id': 'ARG',
  'iso2Code': 'AR',
  'name': 'Argentina',
  'region': {'id': 'LCN',
   'iso2code': 'ZJ',
   'value': 'Latin America & Caribbean '},
  'adminregion': {'id': 'LAC',
   'iso2code': 'XJ',
   'value': 'Latin America & Caribbean (excluding high income)'},
  'incomeLevel': {'id': 'UMC',
   'iso2code': 'XT',
   'value': 'Upper middle income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'Buenos Aires',
  'longitude': '-58.4173',
  'latitude': '-34.6118'},
 {'id': 'ARM',
  'iso2Code': 'AM',
  'name': 'Armenia',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
  'adminregion': {'id': 'ECA',
   'iso2code': '7E',
   'value': 'Europe & Central Asia (excluding high income)'},
  'incomeLevel': {'id': 'UMC',
   'iso2code': 'XT',
   'value': 'Upper middle income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'Yerevan',
  'longitude': '44.509',
  'latitude': '40.1596'},
 {'id': 'ASM',
  'iso2Code': 'AS',
  'name': 'American Samoa',
  'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Pago Pago',
  'longitude': '-170.691',
  'latitude': '-14.2846'},
 {'id': 'ATG',
  'iso2Code': 'AG',
  'name': 'Antigua and Barbuda',
  'region': {'id': 'LCN',
   'iso2code': 'ZJ',
   'value': 'Latin America & Caribbean '},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': "Saint John's",
  'longitude': '-61.8456',
  'latitude': '17.1175'},
 {'id': 'AUS',
  'iso2Code': 'AU',
  'name': 'Australia',
  'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Canberra',
  'longitude': '149.129',
  'latitude': '-35.282'},
 {'id': 'AUT',
  'iso2Code': 'AT',
  'name': 'Austria',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Vienna',
  'longitude': '16.3798',
  'latitude': '48.2201'},
 {'id': 'AZE',
  'iso2Code': 'AZ',
  'name': 'Azerbaijan',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
  'adminregion': {'id': 'ECA',
   'iso2code': '7E',
   'value': 'Europe & Central Asia (excluding high income)'},
  'incomeLevel': {'id': 'UMC',
   'iso2code': 'XT',
   'value': 'Upper middle income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'Baku',
  'longitude': '49.8932',
  'latitude': '40.3834'},
 {'id': 'BDI',
  'iso2Code': 'BI',
  'name': 'Burundi',
  'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
  'adminregion': {'id': 'SSA',
   'iso2code': 'ZF',
   'value': 'Sub-Saharan Africa (excluding high income)'},
  'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'},
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'capitalCity': 'Bujumbura',
  'longitude': '29.3639',
  'latitude': '-3.3784'},
 {'id': 'BEA',
  'iso2Code': 'B4',
  'name': 'East Asia & Pacific (IBRD-only countries)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'BEC',
  'iso2Code': 'B7',
  'name': 'Europe & Central Asia (IBRD-only countries)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'BEL',
  'iso2Code': 'BE',
  'name': 'Belgium',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Brussels',
  'longitude': '4.36761',
  'latitude': '50.8371'},
 {'id': 'BEN',
  'iso2Code': 'BJ',
  'name': 'Benin',
  'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
  'adminregion': {'id': 'SSA',
   'iso2code': 'ZF',
   'value': 'Sub-Saharan Africa (excluding high income)'},
  'incomeLevel': {'id': 'LMC',
   'iso2code': 'XN',
   'value': 'Lower middle income'},
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'capitalCity': 'Porto-Novo',
  'longitude': '2.6323',
  'latitude': '6.4779'},
 {'id': 'BFA',
  'iso2Code': 'BF',
  'name': 'Burkina Faso',
  'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
  'adminregion': {'id': 'SSA',
   'iso2code': 'ZF',
   'value': 'Sub-Saharan Africa (excluding high income)'},
  'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'},
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'capitalCity': 'Ouagadougou',
  'longitude': '-1.53395',
  'latitude': '12.3605'},
 {'id': 'BGD',
  'iso2Code': 'BD',
  'name': 'Bangladesh',
  'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
  'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
  'incomeLevel': {'id': 'LMC',
   'iso2code': 'XN',
   'value': 'Lower middle income'},
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'capitalCity': 'Dhaka',
  'longitude': '90.4113',
  'latitude': '23.7055'},
 {'id': 'BGR',
  'iso2Code': 'BG',
  'name': 'Bulgaria',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'Sofia',
  'longitude': '23.3238',
  'latitude': '42.7105'},
 {'id': 'BHI',
  'iso2Code': 'B1',
  'name': 'IBRD countries classified as high income',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'BHR',
  'iso2Code': 'BH',
  'name': 'Bahrain',
  'region': {'id': 'MEA',
   'iso2code': 'ZQ',
   'value': 'Middle East & North Africa'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Manama',
  'longitude': '50.5354',
  'latitude': '26.1921'},
 {'id': 'BHS',
  'iso2Code': 'BS',
  'name': 'Bahamas, The',
  'region': {'id': 'LCN',
   'iso2code': 'ZJ',
   'value': 'Latin America & Caribbean '},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Nassau',
  'longitude': '-77.339',
  'latitude': '25.0661'},
 {'id': 'BIH',
  'iso2Code': 'BA',
  'name': 'Bosnia and Herzegovina',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
  'adminregion': {'id': 'ECA',
   'iso2code': '7E',
   'value': 'Europe & Central Asia (excluding high income)'},
  'incomeLevel': {'id': 'UMC',
   'iso2code': 'XT',
   'value': 'Upper middle income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'Sarajevo',
  'longitude': '18.4214',
  'latitude': '43.8607'},
 {'id': 'BLA',
  'iso2Code': 'B2',
  'name': 'Latin America & the Caribbean (IBRD-only countries)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'BLR',
  'iso2Code': 'BY',
  'name': 'Belarus',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
  'adminregion': {'id': 'ECA',
   'iso2code': '7E',
   'value': 'Europe & Central Asia (excluding high income)'},
  'incomeLevel': {'id': 'UMC',
   'iso2code': 'XT',
   'value': 'Upper middle income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'Minsk',
  'longitude': '27.5766',
  'latitude': '53.9678'},
 {'id': 'BLZ',
  'iso2Code': 'BZ',
  'name': 'Belize',
  'region': {'id': 'LCN',
   'iso2code': 'ZJ',
   'value': 'Latin America & Caribbean '},
  'adminregion': {'id': 'LAC',
   'iso2code': 'XJ',
   'value': 'Latin America & Caribbean (excluding high income)'},
  'incomeLevel': {'id': 'UMC',
   'iso2code': 'XT',
   'value': 'Upper middle income'},
  'lendingType': {'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'},
  'capitalCity': 'Belmopan',
  'longitude': '-88.7713',
  'latitude': '17.2534'},
 {'id': 'BMN',
  'iso2Code': 'B3',
  'name': 'Middle East & North Africa (IBRD-only countries)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'BMU',
  'iso2Code': 'BM',
  'name': 'Bermuda',
  'region': {'id': 'NAC', 'iso2code': 'XU', 'value': 'North America'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Hamilton',
  'longitude': '-64.706',
  'latitude': '32.3293'},
 {'id': 'BOL',
  'iso2Code': 'BO',
  'name': 'Bolivia',
  'region': {'id': 'LCN',
   'iso2code': 'ZJ',
   'value': 'Latin America & Caribbean '},
  'adminregion': {'id': 'LAC',
   'iso2code': 'XJ',
   'value': 'Latin America & Caribbean (excluding high income)'},
  'incomeLevel': {'id': 'LMC',
   'iso2code': 'XN',
   'value': 'Lower middle income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'La Paz',
  'longitude': '-66.1936',
  'latitude': '-13.9908'},
 {'id': 'BRA',
  'iso2Code': 'BR',
  'name': 'Brazil',
  'region': {'id': 'LCN',
   'iso2code': 'ZJ',
   'value': 'Latin America & Caribbean '},
  'adminregion': {'id': 'LAC',
   'iso2code': 'XJ',
   'value': 'Latin America & Caribbean (excluding high income)'},
  'incomeLevel': {'id': 'UMC',
   'iso2code': 'XT',
   'value': 'Upper middle income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'Brasilia',
  'longitude': '-47.9292',
  'latitude': '-15.7801'},
 {'id': 'BRB',
  'iso2Code': 'BB',
  'name': 'Barbados',
  'region': {'id': 'LCN',
   'iso2code': 'ZJ',
   'value': 'Latin America & Caribbean '},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'Bridgetown',
  'longitude': '-59.6105',
  'latitude': '13.0935'},
 {'id': 'BRN',
  'iso2Code': 'BN',
  'name': 'Brunei Darussalam',
  'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Bandar Seri Begawan',
  'longitude': '114.946',
  'latitude': '4.94199'},
 {'id': 'BSS',
  'iso2Code': 'B6',
  'name': 'Sub-Saharan Africa (IBRD-only countries)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'BTN',
  'iso2Code': 'BT',
  'name': 'Bhutan',
  'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
  'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
  'incomeLevel': {'id': 'LMC',
   'iso2code': 'XN',
   'value': 'Lower middle income'},
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'capitalCity': 'Thimphu',
  'longitude': '89.6177',
  'latitude': '27.5768'},
 {'id': 'BWA',
  'iso2Code': 'BW',
  'name': 'Botswana',
  'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
  'adminregion': {'id': 'SSA',
   'iso2code': 'ZF',
   'value': 'Sub-Saharan Africa (excluding high income)'},
  'incomeLevel': {'id': 'UMC',
   'iso2code': 'XT',
   'value': 'Upper middle income'},
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'capitalCity': 'Gaborone',
  'longitude': '25.9201',
  'latitude': '-24.6544'},
 {'id': 'CAA',
  'iso2Code': 'C9',
  'name': 'Sub-Saharan Africa (IFC classification)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'CAF',
  'iso2Code': 'CF',
  'name': 'Central African Republic',
  'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
  'adminregion': {'id': 'SSA',
   'iso2code': 'ZF',
   'value': 'Sub-Saharan Africa (excluding high income)'},
  'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'},
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'capitalCity': 'Bangui',
  'longitude': '21.6407',
  'latitude': '5.63056'},
 {'id': 'CAN',
  'iso2Code': 'CA',
  'name': 'Canada',
  'region': {'id': 'NAC', 'iso2code': 'XU', 'value': 'North America'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'capitalCity': 'Ottawa',
  'longitude': '-75.6919',
  'latitude': '45.4215'},
 {'id': 'CEA',
  'iso2Code': 'C4',
  'name': 'East Asia and the Pacific (IFC classification)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'capitalCity': '',
  'longitude': '',
  'latitude': ''},
 {'id': 'CEB',
  'iso2Code': 'B8',

In [27]:
pd.DataFrame(res3[1])

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
2,AFG,AF,Afghanistan,"{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout...","{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228
3,AFR,A9,Africa,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
4,AFW,ZI,Africa Western and Central,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
...,...,...,...,...,...,...,...,...,...,...
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
292,YEM,YE,"Yemen, Rep.","{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Sana'a,44.2075,15.352
293,ZAF,ZA,South Africa,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Pretoria,28.1871,-25.746
294,ZMB,ZM,Zambia,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Lusaka,28.2937,-15.3982
295,ZWE,ZW,Zimbabwe,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}",Harare,31.0672,-17.8312

In [28]:
Countries = pd.json_normalize(res3[1])

In [29]:
Countries = Countries.drop(['iso2Code','region.id','region.iso2code','adminregion.id','adminregion.iso2code','incomeLevel.id','incomeLevel.iso2code','lendingType.id','lendingType.iso2code'], axis = 1)

In [30]:
Countries

,id,name,capitalCity,longitude,latitude,region.value,adminregion.value,incomeLevel.value,lendingType.value
0,ABW,Aruba,Oranjestad,-70.0167,12.5167,Latin America & Caribbean,,High income,Not classified
1,AFE,Africa Eastern and Southern,,,,Aggregates,,Aggregates,Aggregates
2,AFG,Afghanistan,Kabul,69.1761,34.5228,South Asia,South Asia,Low income,IDA
3,AFR,Africa,,,,Aggregates,,Aggregates,Aggregates
4,AFW,Africa Western and Central,,,,Aggregates,,Aggregates,Aggregates
...,...,...,...,...,...,...,...,...,...
291,XZN,Sub-Saharan Africa excluding South Africa and ...,,,,Aggregates,,Aggregates,Aggregates
292,YEM,"Yemen, Rep.",Sana'a,44.2075,15.352,Middle East & North Africa,Middle East & North Africa (excluding high inc...,Low income,IDA
293,ZAF,South Africa,Pretoria,28.1871,-25.746,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Upper middle income,IBRD
294,ZMB,Zambia,Lusaka,28.2937,-15.3982,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IDA
295,ZWE,Zimbabwe,Harare,31.0672,-17.8312,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend

In [31]:
gdp_merged.rename(columns = {'countryiso3code':'id'}, inplace = True)

In [32]:
gdp_merged = gdp_merged.drop(['_merge'], axis = 1)

In [33]:
countries_Merged = pd.merge(
    left = gdp_merged, 
    right = Countries, 
    left_on = 'id', 
    right_on = 'id',
    validate = "many_to_one",
    how = 'left',
    indicator = True
)
countries_Merged

,id,Year,GDP_Per_Capita,country.id,country.value,Life_Exp,name,capitalCity,longitude,latitude,region.value,adminregion.value,incomeLevel.value,lendingType.value,_merge
0,AFE,2023,4047.007031,ZH,Africa Eastern and Southern,NaN,Africa Eastern and Southern,,,,Aggregates,,Aggregates,Aggregates,both
1,AFE,2022,4038.638689,ZH,Africa Eastern and Southern,62.899031,Africa Eastern and Southern,,,,Aggregates,,Aggregates,Aggregates,both
2,AFE,2021,3994.171654,ZH,Africa Eastern and Southern,62.454590,Africa Eastern and Southern,,,,Aggregates,,Aggregates,Aggregates,both
3,AFE,2020,3919.499230,ZH,Africa Eastern and Southern,63.313860,Africa Eastern and Southern,,,,Aggregates,,Aggregates,Aggregates,both
4,AFE,2019,4130.057222,ZH,Africa Eastern and Southern,63.755678,Africa Eastern and Southern,,,,Aggregates,,Aggregates,Aggregates,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17019,ZWE,1964,NaN,ZW,Zimbabwe,54.994000,Zimbabwe,Harare,31.0672,-17.8312,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,both
17020,ZWE,1963,NaN,ZW,Zimbabwe,54.549000,Zimbabwe,Harare,31.0672,-17.8312,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,both
17021,ZWE,1962,NaN,ZW,Zimbabwe,54.071000,Zimbabwe,Harare,31.0672,-17.8312,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,both
17022,ZWE,1961,NaN,ZW,Zimbabwe,53.619000,Zimbabwe,Harare,31.0672,-17.8312,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,both
17023,ZWE,1960,NaN,ZW,Zimbabwe,53.235000,Zimbabwe,Harare,31.0672,-17.8312,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,both

In [34]:
countries_Merged.sample(10)

,id,Year,GDP_Per_Capita,country.id,country.value,Life_Exp,name,capitalCity,longitude,latitude,region.value,adminregion.value,incomeLevel.value,lendingType.value,_merge
9001,IRN,1982,NaN,IR,"Iran, Islamic Rep.",57.734,"Iran, Islamic Rep.",Tehran,51.4447,35.6878,Middle East & North Africa,Middle East & North Africa (excluding high inc...,Upper middle income,IBRD,both
12695,PAK,2000,3543.362586,PK,Pakistan,62.102,Pakistan,Islamabad,72.8,30.5167,South Asia,South Asia,Lower middle income,Blend,both
11933,NRU,1994,11089.237009,NR,Nauru,61.463,Nauru,Yaren District,166.920867,-0.5477,East Asia & Pacific,,High income,IBRD,both
3159,AFG,2000,1666.448650,AF,Afghanistan,55.298,Afghanistan,Kabul,69.1761,34.5228,South Asia,South Asia,Low income,IDA,both
8388,GNB,2019,2205.986945,GW,Guinea-Bissau,60.882,Guinea-Bissau,Bissau,-15.1804,11.8037,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Low income,IDA,both
5645,CHI,2010,NaN,JG,Channel Islands,81.120,Channel Islands,,,,Europe & Central Asia,,High income,Not classified,both
15313,TJK,2006,2063.332070,TJ,Tajikistan,67.013,Tajikistan,Dushanbe,68.7864,38.5878,Europe & Central Asia,Europe & Central Asia (excluding high income),Lower middle income,IDA,both
7177,SWZ,2014,8947.763656,SZ,Eswatini,53.050,Eswatini,Mbabane,31.4659,-26.5225,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,both
7745,GEO,2022,20966.528039,GE,Georgia,71.587,Georgia,Tbilisi,44.793,41.71,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,both
9081,IRQ,1966,NaN,IQ,Iraq,57.348,Iraq,Baghdad,44.394,33.3302,Middle East & North Africa,Middle East & North Africa (excluding high inc...,Upper middle income,IBRD,both

In [35]:
countries_Merged = countries_Merged.drop(['id','country.id','name','region.value','adminregion.value'], axis = 1)

In [36]:
countries_Merged

,Year,GDP_Per_Capita,country.value,Life_Exp,capitalCity,longitude,latitude,incomeLevel.value,lendingType.value,_merge
0,2023,4047.007031,Africa Eastern and Southern,NaN,,,,Aggregates,Aggregates,both
1,2022,4038.638689,Africa Eastern and Southern,62.899031,,,,Aggregates,Aggregates,both
2,2021,3994.171654,Africa Eastern and Southern,62.454590,,,,Aggregates,Aggregates,both
3,2020,3919.499230,Africa Eastern and Southern,63.313860,,,,Aggregates,Aggregates,both
4,2019,4130.057222,Africa Eastern and Southern,63.755678,,,,Aggregates,Aggregates,both
...,...,...,...,...,...,...,...,...,...,...
17019,1964,NaN,Zimbabwe,54.994000,Harare,31.0672,-17.8312,Lower middle income,Blend,both
17020,1963,NaN,Zimbabwe,54.549000,Harare,31.0672,-17.8312,Lower middle income,Blend,both
17021,1962,NaN,Zimbabwe,54.071000,Harare,31.0672,-17.8312,Lower middle income,Blend,both
17022,1961,NaN,Zimbabwe,53.619000,Harare,31.0672,-17.8312,Lower middle income,Blend,both
17023,1960,NaN,Zimbabwe,53.235000,Harare,31.0672,-17.8312,Lower middle income,Blend,both

In [37]:
countries_Merged.rename(columns = {'date':'Year','country':'Country','capitalCity':'Capital','longitude':'long','latitude':'lat','incomeLevel.value':'incomeLevel','lendingType.value':'lendingType'}, inplace = True)

In [38]:
countries_Merged

,Year,GDP_Per_Capita,country.value,Life_Exp,Capital,long,lat,incomeLevel,lendingType,_merge
0,2023,4047.007031,Africa Eastern and Southern,NaN,,,,Aggregates,Aggregates,both
1,2022,4038.638689,Africa Eastern and Southern,62.899031,,,,Aggregates,Aggregates,both
2,2021,3994.171654,Africa Eastern and Southern,62.454590,,,,Aggregates,Aggregates,both
3,2020,3919.499230,Africa Eastern and Southern,63.313860,,,,Aggregates,Aggregates,both
4,2019,4130.057222,Africa Eastern and Southern,63.755678,,,,Aggregates,Aggregates,both
...,...,...,...,...,...,...,...,...,...,...
17019,1964,NaN,Zimbabwe,54.994000,Harare,31.0672,-17.8312,Lower middle income,Blend,both
17020,1963,NaN,Zimbabwe,54.549000,Harare,31.0672,-17.8312,Lower middle income,Blend,both
17021,1962,NaN,Zimbabwe,54.071000,Harare,31.0672,-17.8312,Lower middle income,Blend,both
17022,1961,NaN,Zimbabwe,53.619000,Harare,31.0672,-17.8312,Lower middle income,Blend,both
17023,1960,NaN,Zimbabwe,53.235000,Harare,31.0672,-17.8312,Lower middle income,Blend,both

### BONUS QUESTIONS

## #1)

In [40]:
endpoint = 'https://api.worldbank.org/v2/country/us/indicator/NY.GDP.PCAP.PP.KD'

params = {
    'format': 'json',
    'per_page': 64
}

response = requests.get(endpoint, params = params)
res = response.json()
gdp_ppp = pd.json_normalize(res[1])
gdp_ppp = gdp_ppp.drop(['indicator.id','indicator.value','decimal','unit','obs_status'], axis = 1)
gdp_ppp.rename(columns = {'value':'GDP_Per_Capita','date':'Year'}, inplace = True)

########################################################

endpoint2 = 'https://api.worldbank.org/v2/country/us/indicator/SP.DYN.LE00.IN'

params2 = {
    'format': 'json',
    'per_page': 64
}

response2 = requests.get(endpoint2, params = params2)
res2 = response2.json()
LifeExp_TotYears = pd.json_normalize(res2[1])
LifeExp_TotYears = LifeExp_TotYears.drop(['unit','obs_status','decimal','indicator.id','indicator.value'], axis = 1)
LifeExp_TotYears.rename(columns = {'value':'Life_Exp','date':'Year'}, inplace = True)

#################################################################

gdp_merged = pd.merge(
    left = gdp_ppp, 
    right = LifeExp_TotYears, 
    indicator = True
)

gdp_merged.rename(columns = {'countryiso3code':'id'}, inplace = True)
gdp_merged = gdp_merged.drop(['_merge'], axis = 1)

#######################################################

endpoint3 = 'https://api.worldbank.org/v2/country/us'

params3 = {
    'format': 'json',
    'per_page': 1
}

response3 = requests.get(endpoint3, params = params3)
res3 = response3.json()
Countries = pd.json_normalize(res3[1])
Countries = Countries.drop(['iso2Code','region.id','region.iso2code','adminregion.id','adminregion.iso2code','incomeLevel.id','incomeLevel.iso2code','lendingType.id','lendingType.iso2code'], axis = 1)

###########################################################

countries_Merged = pd.merge(
    left = gdp_merged, 
    right = Countries, 
    left_on = 'id', 
    right_on = 'id',
    validate = "many_to_one",
    how = 'left',
    indicator = True
)
countries_Merged = countries_Merged.drop(['id','country.id','name','region.value','adminregion.value'], axis = 1)
countries_Merged.rename(columns = {'date':'Year','country':'Country','capitalCity':'Capital','longitude':'long','latitude':'lat','incomeLevel.value':'incomeLevel','lendingType.value':'lendingType'}, inplace = True)
countries_Merged

,Year,GDP_Per_Capita,country.value,Life_Exp,Capital,long,lat,incomeLevel,lendingType,_merge
0,2023,73637.302789,United States,NaN,Washington D.C.,-77.032,38.8895,High income,Not classified,both
1,2022,72165.483470,United States,77.434146,Washington D.C.,-77.032,38.8895,High income,Not classified,both
2,2021,71055.876194,United States,76.329268,Washington D.C.,-77.032,38.8895,High income,Not classified,both
3,2020,67266.187874,United States,76.980488,Washington D.C.,-77.032,38.8895,High income,Not classified,both
4,2019,69458.610183,United States,78.787805,Washington D.C.,-77.032,38.8895,High income,Not classified,both
...,...,...,...,...,...,...,...,...,...,...
59,1964,NaN,United States,70.165854,Washington D.C.,-77.032,38.8895,High income,Not classified,both
60,1963,NaN,United States,69.917073,Washington D.C.,-77.032,38.8895,High income,Not classified,both
61,1962,NaN,United States,70.119512,Washington D.C.,-77.032,38.8895,High income,Not classified,both
62,1961,NaN,United States,70.270732,Washington D.C.,-77.032,38.8895,High income,Not classified,both
63,1960,NaN,United States,69.770732,Washington D.C.,-77.032,38.8895,High income,Not classified,both

## #2)

In [41]:
endpoint = 'https://api.worldbank.org/v2/country/us/indicator/NY.GDP.PCAP.PP.KD'

params = {
    'format': 'json',
    'per_page': 1,
    'date':'2021'
}

response = requests.get(endpoint, params = params)
res = response.json()
gdp_ppp = pd.json_normalize(res[1])
gdp_ppp = gdp_ppp.drop(['indicator.id','indicator.value','decimal','unit','obs_status'], axis = 1)
gdp_ppp.rename(columns = {'value':'GDP_Per_Capita','date':'Year'}, inplace = True)

########################################################

endpoint2 = 'https://api.worldbank.org/v2/country/us/indicator/SP.DYN.LE00.IN'

params2 = {
    'format': 'json',
    'per_page': 1,
    'date':'2021'
}

response2 = requests.get(endpoint2, params = params2)
res2 = response2.json()
LifeExp_TotYears = pd.json_normalize(res2[1])
LifeExp_TotYears = LifeExp_TotYears.drop(['unit','obs_status','decimal','indicator.id','indicator.value'], axis = 1)
LifeExp_TotYears.rename(columns = {'value':'Life_Exp','date':'Year'}, inplace = True)

#################################################################

gdp_merged = pd.merge(
    left = gdp_ppp, 
    right = LifeExp_TotYears, 
    indicator = True
)

gdp_merged.rename(columns = {'countryiso3code':'id'}, inplace = True)
gdp_merged = gdp_merged.drop(['_merge'], axis = 1)

#######################################################

endpoint3 = 'https://api.worldbank.org/v2/country/us'

params3 = {
    'format': 'json',
    'per_page': 1,
    'date':'2021'
}

response3 = requests.get(endpoint3, params = params3)
res3 = response3.json()
Countries = pd.json_normalize(res3[1])
Countries = Countries.drop(['iso2Code','region.id','region.iso2code','adminregion.id','adminregion.iso2code','incomeLevel.id','incomeLevel.iso2code','lendingType.id','lendingType.iso2code'], axis = 1)

###########################################################

countries_Merged = pd.merge(
    left = gdp_merged, 
    right = Countries, 
    left_on = 'id', 
    right_on = 'id',
    validate = "many_to_one",
    how = 'left',
    indicator = True
)
countries_Merged = countries_Merged.drop(['id','country.id','name','region.value','adminregion.value'], axis = 1)
countries_Merged.rename(columns = {'date':'Year','country':'Country','capitalCity':'Capital','longitude':'long','latitude':'lat','incomeLevel.value':'incomeLevel','lendingType.value':'lendingType'}, inplace = True)
countries_Merged

,Year,GDP_Per_Capita,country.value,Life_Exp,Capital,long,lat,incomeLevel,lendingType,_merge
0,2021,71055.876194,United States,76.329268,Washington D.C.,-77.032,38.8895,High income,Not classified,both

## #3)

In [42]:
endpoint = 'https://api.worldbank.org/v2/country/us/indicator/NY.GDP.PCAP.PP.KD'

params = {
    'format': 'json',
    'per_page': 22,
    'date':'2000:2021'
}

response = requests.get(endpoint, params = params)
res = response.json()
gdp_ppp = pd.json_normalize(res[1])
gdp_ppp = gdp_ppp.drop(['indicator.id','indicator.value','decimal','unit','obs_status'], axis = 1)
gdp_ppp.rename(columns = {'value':'GDP_Per_Capita','date':'Year'}, inplace = True)

########################################################

endpoint2 = 'https://api.worldbank.org/v2/country/us/indicator/SP.DYN.LE00.IN'

params2 = {
    'format': 'json',
    'per_page': 22,
    'date':'2000:2021'
}

response2 = requests.get(endpoint2, params = params2)
res2 = response2.json()
LifeExp_TotYears = pd.json_normalize(res2[1])
LifeExp_TotYears = LifeExp_TotYears.drop(['unit','obs_status','decimal','indicator.id','indicator.value'], axis = 1)
LifeExp_TotYears.rename(columns = {'value':'Life_Exp','date':'Year'}, inplace = True)

#################################################################

gdp_merged = pd.merge(
    left = gdp_ppp, 
    right = LifeExp_TotYears, 
    indicator = True
)

gdp_merged.rename(columns = {'countryiso3code':'id'}, inplace = True)
gdp_merged = gdp_merged.drop(['_merge'], axis = 1)

#######################################################

endpoint3 = 'https://api.worldbank.org/v2/country/us'

params3 = {
    'format': 'json',
    'per_page': 1,
    'date':'2000:2021'
}

response3 = requests.get(endpoint3, params = params3)
res3 = response3.json()
Countries = pd.json_normalize(res3[1])
Countries = Countries.drop(['iso2Code','region.id','region.iso2code','adminregion.id','adminregion.iso2code','incomeLevel.id','incomeLevel.iso2code','lendingType.id','lendingType.iso2code'], axis = 1)

###########################################################

countries_Merged = pd.merge(
    left = gdp_merged, 
    right = Countries, 
    left_on = 'id', 
    right_on = 'id',
    validate = "many_to_one",
    how = 'left',
    indicator = True
)
countries_Merged = countries_Merged.drop(['id','country.id','name','region.value','adminregion.value'], axis = 1)
countries_Merged.rename(columns = {'date':'Year','country':'Country','capitalCity':'Capital','longitude':'long','latitude':'lat','incomeLevel.value':'incomeLevel','lendingType.value':'lendingType'}, inplace = True)
countries_Merged

,Year,GDP_Per_Capita,country.value,Life_Exp,Capital,long,lat,incomeLevel,lendingType,_merge
0,2021,71055.876194,United States,76.329268,Washington D.C.,-77.032,38.8895,High income,Not classified,both
1,2020,67266.187874,United States,76.980488,Washington D.C.,-77.032,38.8895,High income,Not classified,both
2,2019,69458.610183,United States,78.787805,Washington D.C.,-77.032,38.8895,High income,Not classified,both
3,2018,68095.686806,United States,78.639024,Washington D.C.,-77.032,38.8895,High income,Not classified,both
4,2017,66482.893439,United States,78.539024,Washington D.C.,-77.032,38.8895,High income,Not classified,both
5,2016,65299.999384,United States,78.539024,Washington D.C.,-77.032,38.8895,High income,Not classified,both
6,2015,64599.573736,United States,78.690244,Washington D.C.,-77.032,38.8895,High income,Not classified,both
7,2014,63214.895346,United States,78.841463,Washington D.C.,-77.032,38.8895,High income,Not classified,both
8,2013,62112.583447,United States,78.741463,Washington D.C.,-77.032,38.8895,High income,Not classified,both
9,2012,61247.317072,United States,78.741463,Washington D.C.,-77.032,38.8895,High income,Not classified,both
10,2011,60317.542521,United States,78.641463,Washington D.C.,-77.032,38.8895,High income,Not classified,both
11,2010,59821.665081,United States,78.541463,Washington D.C.,-77.032,38.8895,High income,Not classified,both
12,2009,58736.946133,United States,78.390244,Washington D.C.,-77.032,38.8895,High income,Not classified,both
13,2008,60821.185961,United States,78.039024,Washington D.C.,-77.032,38.8895,High income,Not classified,both
14,2007,61329.539227,United States,77.987805,Washington D.C.,-77.032,38.8895,High income,Not classified,both
15,2006,60699.272085,United States,77.687805,Washington D.C.,-77.032,38.8895,High income,Not classified,both
16,2005,59627.059056,United States,77.487805,Washington D.C.,-77.032,38.8895,High income,Not classified,both
17,2004,58153.387828,United States,77.487805,Washington D.C.,-77.032,38.8895,High income,Not classified,both
18,2003,56519.350712,United States,77.036585,Washington D.C.,-77.032,38.8895,High income,Not classified,both
19,2002,55456.862403,United States,76.936585,Washington D.C.,-77.032,38.8895,High income,Not classified,both
20,2001,55037.893673,United States,76.836585,Washington D.C.,-77.032,38.8895,High income,Not classified,both
21,2000,55059.219169,United States,76.636585,Washington D.C.,-77.032,38.8895,High income,Not classified,both

## #4)

In [43]:
endpoint = 'https://api.worldbank.org/v2/country/us;can/indicator/NY.GDP.PCAP.PP.KD'

params = {
    'format': 'json',
    'per_page': 44,
    'date':'2000:2021'
}

response = requests.get(endpoint, params = params)
res = response.json()
gdp_ppp = pd.json_normalize(res[1])
gdp_ppp = gdp_ppp.drop(['indicator.id','indicator.value','decimal','unit','obs_status'], axis = 1)
gdp_ppp.rename(columns = {'value':'GDP_Per_Capita','date':'Year'}, inplace = True)

########################################################

endpoint2 = 'https://api.worldbank.org/v2/country/us;can/indicator/SP.DYN.LE00.IN'

params2 = {
    'format': 'json',
    'per_page': 44,
    'date':'2000:2021'
}

response2 = requests.get(endpoint2, params = params2)
res2 = response2.json()
LifeExp_TotYears = pd.json_normalize(res2[1])
LifeExp_TotYears = LifeExp_TotYears.drop(['unit','obs_status','decimal','indicator.id','indicator.value'], axis = 1)
LifeExp_TotYears.rename(columns = {'value':'Life_Exp','date':'Year'}, inplace = True)

#################################################################

gdp_merged = pd.merge(
    left = gdp_ppp, 
    right = LifeExp_TotYears, 
    indicator = True
)

gdp_merged.rename(columns = {'countryiso3code':'id'}, inplace = True)
gdp_merged = gdp_merged.drop(['_merge'], axis = 1)

#######################################################

endpoint3 = 'https://api.worldbank.org/v2/country/us;can'

params3 = {
    'format': 'json',
    'per_page': 2,
    'date':'2000:2021'
}

response3 = requests.get(endpoint3, params = params3)
res3 = response3.json()
Countries = pd.json_normalize(res3[1])
Countries = Countries.drop(['iso2Code','region.id','region.iso2code','adminregion.id','adminregion.iso2code','incomeLevel.id','incomeLevel.iso2code','lendingType.id','lendingType.iso2code'], axis = 1)

###########################################################

countries_Merged = pd.merge(
    left = gdp_merged, 
    right = Countries, 
    left_on = 'id', 
    right_on = 'id',
    validate = "many_to_one",
    how = 'left',
    indicator = True
)
countries_Merged = countries_Merged.drop(['id','country.id','name','region.value','adminregion.value'], axis = 1)
countries_Merged.rename(columns = {'date':'Year','country':'Country','capitalCity':'Capital','longitude':'long','latitude':'lat','incomeLevel.value':'incomeLevel','lendingType.value':'lendingType'}, inplace = True)
countries_Merged

,Year,GDP_Per_Capita,country.value,Life_Exp,Capital,long,lat,incomeLevel,lendingType,_merge
0,2021,55781.699027,Canada,81.587073,Ottawa,-75.6919,45.4215,High income,Not classified,both
1,2020,53274.910930,Canada,81.660488,Ottawa,-75.6919,45.4215,High income,Not classified,both
2,2019,56713.088877,Canada,82.223902,Ottawa,-75.6919,45.4215,High income,Not classified,both
3,2018,56470.459267,Canada,81.843902,Ottawa,-75.6919,45.4215,High income,Not classified,both
4,2017,55756.262482,Canada,81.832927,Ottawa,-75.6919,45.4215,High income,Not classified,both
5,2016,54765.303772,Canada,81.924878,Ottawa,-75.6919,45.4215,High income,Not classified,both
6,2015,54819.189035,Canada,81.815610,Ottawa,-75.6919,45.4215,High income,Not classified,both
7,2014,54880.858202,Canada,81.784390,Ottawa,-75.6919,45.4215,High income,Not classified,both
8,2013,53884.845588,Canada,81.744878,Ottawa,-75.6919,45.4215,High income,Not classified,both
9,2012,53217.713583,Canada,81.663659,Ottawa,-75.6919,45.4215,High income,Not classified,both
10,2011,52869.387856,Canada,81.482683,Ottawa,-75.6919,45.4215,High income,Not classified,both
11,2010,51763.675810,Canada,81.322195,Ottawa,-75.6919,45.4215,High income,Not classified,both
12,2009,50772.869922,Canada,81.066098,Ottawa,-75.6919,45.4215,High income,Not classified,both
13,2008,52899.475450,Canada,80.724634,Ottawa,-75.6919,45.4215,High income,Not classified,both
14,2007,52948.899427,Canada,80.543659,Ottawa,-75.6919,45.4215,High income,Not classified,both
15,2006,52391.379262,Canada,80.543659,Ottawa,-75.6919,45.4215,High income,Not classified,both
16,2005,51564.845565,Canada,80.112683,Ottawa,-75.6919,45.4215,High income,Not classified,both
17,2004,50436.294843,Canada,79.992195,Ottawa,-75.6919,45.4215,High income,Not classified,both
18,2003,49381.595036,Canada,79.715122,Ottawa,-75.6919,45.4215,High income,Not classified,both
19,2002,48943.541241,Canada,79.530732,Ottawa,-75.6919,45.4215,High income,Not classified,both
20,2001,48036.626618,Canada,79.398049,Ottawa,-75.6919,45.4215,High income,Not classified,both
21,2000,47667.433086,Canada,79.166829,Ottawa,-75.6919,45.4215,High income,Not classified,both
22,2021,71055.876194,United States,76.329268,Washington D.C.,-77.032,38.8895,High income,Not classified,both
23,2020,67266.187874,United States,76.980488,Washington D.C.,-77.032,38.8895,High income,Not classified,both
24,2019,69458.610183,United States,78.787805,Washington D.C.,-77.032,38.8895,High income,Not classified,both
25,2018,68095.686806,United States,78.639024,Washington D.C.,-77.032,38.8895,High income,Not classified,both
26,2017,66482.893439,United States,78.539024,Washington D.C.,-77.032,38.8895,High income,Not classified,both
27,2016,65299.999384,United States,78.539024,Washington D.C.,-77.032,38.8895,High income,Not classified,both
28,2015,64599.573736,United States,78.690244,Washington D.C.,-77.032,38.8895,High income,Not classified,both
29,2014,63214.895346,United States,78.841463,Washington D.C.,-77.032,38.8895,High income,Not classified,both
30,2013,62112.583447,United States,78.741463,Washington D.C.,-77.032,38.8895,High income,Not classified,both
31,2012,61247.317072,United States,78.741463,Washington D.C.,-77.032,38.8895,High income,Not classified,both
32,2011,60317.542521,United States,78.641463,Washington D.C.,-77.032,38.8895,High income,Not classified,both
33,2010,59821.665081,United States,78.541463,Washington D.C.,-77.032,38.8895,High income,Not classified,both
34,2009,58736.946133,United States,78.390244,Washington D.C.,-77.032,38.8895,High income,Not classified,both
35,2008,60821.185961,United States,78.039024,Washington D.C.,-77.032,38.8895,High income,Not classified,both
36,2007,61329.539227,United States,77.987805,Washington D.C.,-77.032,38.8895,High income,Not classified,both
37,2006,60699.272085,United States,77.687805,Washington D.C.,-77.032,38.8895,High income,Not classified,both
38,2005,59627.059056,United States,77.487805,Washington D.C.,-77.032,38.8895,High income,Not classified,both
39,2004,58153.387828,United States,77.487805,Washington D.C.,-77.032,38.8895,High income,Not classified,both
40,2003,56519.350712,United States,77.036585,Washington D.C.,-77.032,38.8895,High income,Not classified,both
41,2002,55456.862403,United States,76.936585,Washington D.C.,-77.032,38.8895,High income,Not classified,both
42,2001,55037.893673,United States,76.836585,Washington D.C.,-77.032,38.8895,High income,Not classified,both
43,2000,55059.219169,United States,76.636585,Washington D.C.,-77.032,38.8895,High income,Not classified,both

## #5)

In [129]:
endpoint = 'https://api.worldbank.org/v2/country/us;can/indicator/NY.GDP.PCAP.PP.KD'

params = {
    'format': 'json', 
    'page': 1, 
    'date':'2000:2021'
}

response = requests.get(endpoint, params = params)
res = response.json()
df = pd.json_normalize(res[1])
df

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,CAN,2021,55781.699027,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
1,CAN,2020,53274.910930,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
2,CAN,2019,56713.088877,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
3,CAN,2018,56470.459267,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
4,CAN,2017,55756.262482,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
5,CAN,2016,54765.303772,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
6,CAN,2015,54819.189035,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
7,CAN,2014,54880.858202,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
8,CAN,2013,53884.845588,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
9,CAN,2012,53217.713583,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
10,CAN,2011,52869.387856,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
11,CAN,2010,51763.675810,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
12,CAN,2009,50772.869922,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
13,CAN,2008,52899.475450,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
14,CAN,2007,52948.899427,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
15,CAN,2006,52391.379262,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
16,CAN,2005,51564.845565,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
17,CAN,2004,50436.294843,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
18,CAN,2003,49381.595036,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
19,CAN,2002,48943.541241,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
20,CAN,2001,48036.626618,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
21,CAN,2000,47667.433086,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
22,USA,2021,71055.876194,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
23,USA,2020,67266.187874,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
24,USA,2019,69458.610183,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
25,USA,2018,68095.686806,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
26,USA,2017,66482.893439,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
27,USA,2016,65299.999384,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
28,USA,2015,64599.573736,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
29,USA,2014,63214.895346,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
30,USA,2013,62112.583447,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
31,USA,2012,61247.317072,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
32,USA,2011,60317.542521,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
33,USA,2010,59821.665081,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
34,USA,2009,58736.946133,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
35,USA,2008,60821.185961,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
36,USA,2007,61329.539227,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
37,USA,2006,60699.272085,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
38,USA,2005,59627.059056,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
39,USA,2004,58153.387828,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
40,USA,2003,56519.350712,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
41,USA,2002,55456.862403,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
42,USA,2001,55037.893673,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
43,USA,2000,55059.219169,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States

In [61]:
def get_all_records_json(endpoint, params, normalize = False):
    
    """
    This function takes in an endpoint to data formatted as string, and params as a dictionary (no per_pages), and 
    an option to normalize the data and will gather all of the data from that endpoint with params and turn it
    into a dataframe.
    
    
    """

    response = requests.get(endpoint, params = params)
    res = response.json()
    total_pages = res[0]['total']
    
    new_params = params
    new_params['per_page'] = total_pages
    
    response = requests.get(endpoint, params=params)
    res = response.json()
    
    if normalize:
        df = pd.json_normalize(res[1])
    else:
        df = pd.DataFrame(res[1])
    
    return df


endpoint5 = 'https://api.worldbank.org/v2/country/us;can/indicator/NY.GDP.PCAP.PP.KD'
params5 =  {
    'format': 'json',
    'date':'2000:2021'
}

get_all_records_json(endpoint5,params5, normalize = True)

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,CAN,2021,55781.699027,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
1,CAN,2020,53274.910930,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
2,CAN,2019,56713.088877,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
3,CAN,2018,56470.459267,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
4,CAN,2017,55756.262482,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
5,CAN,2016,54765.303772,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
6,CAN,2015,54819.189035,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
7,CAN,2014,54880.858202,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
8,CAN,2013,53884.845588,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
9,CAN,2012,53217.713583,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
10,CAN,2011,52869.387856,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
11,CAN,2010,51763.675810,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
12,CAN,2009,50772.869922,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
13,CAN,2008,52899.475450,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
14,CAN,2007,52948.899427,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
15,CAN,2006,52391.379262,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
16,CAN,2005,51564.845565,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
17,CAN,2004,50436.294843,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
18,CAN,2003,49381.595036,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
19,CAN,2002,48943.541241,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
20,CAN,2001,48036.626618,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
21,CAN,2000,47667.433086,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
22,USA,2021,71055.876194,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
23,USA,2020,67266.187874,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
24,USA,2019,69458.610183,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
25,USA,2018,68095.686806,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
26,USA,2017,66482.893439,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
27,USA,2016,65299.999384,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
28,USA,2015,64599.573736,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
29,USA,2014,63214.895346,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
30,USA,2013,62112.583447,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
31,USA,2012,61247.317072,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
32,USA,2011,60317.542521,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
33,USA,2010,59821.665081,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
34,USA,2009,58736.946133,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
35,USA,2008,60821.185961,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
36,USA,2007,61329.539227,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
37,USA,2006,60699.272085,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
38,USA,2005,59627.059056,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
39,USA,2004,58153.387828,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
40,USA,2003,56519.350712,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
41,USA,2002,55456.862403,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
42,USA,2001,55037.893673,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
43,USA,2000,55059.219169,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States

## #6)

In [123]:
endpointall = 'http://api.worldbank.org/v2/indicator'
paramsall =  {
    'format': 'json',
}


indicators = get_all_records_json(endpointall,paramsall, normalize = True)
indicators

,id,name,unit,sourceNote,sourceOrganization,topics,source.id,source.value
0,1.0.HCount.1.90usd,Poverty Headcount ($1.90 a day),,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]",37,LAC Equity Lab
1,1.0.HCount.2.5usd,Poverty Headcount ($2.50 a day),,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]",37,LAC Equity Lab
2,1.0.HCount.Mid10to50,Middle Class ($10-50 a day) Headcount,,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]",37,LAC Equity Lab
3,1.0.HCount.Ofcl,Official Moderate Poverty Rate-National,,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of data from Nation...,"[{'id': '11', 'value': 'Poverty '}]",37,LAC Equity Lab
4,1.0.HCount.Poor4uds,Poverty Headcount ($4 a day),,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]",37,LAC Equity Lab
...,...,...,...,...,...,...,...,...
24597,WP15163_4.3,"Mobile account, female (% age 15+)",,Mobile account denotes the percentage of respo...,"Demirguc-Kunt et al., 2015, Global Financial I...","[{'id': '7', 'value': 'Financial Sector '}, {'...",57,WDI Database Archives
24598,WP15163_4.8,"Mobile account, income, poorest 40% (% ages 15+)",,Mobile account denotes the percentage of respo...,"Demirguc-Kunt et al., 2015, Global Financial I...","[{'id': '7', 'value': 'Financial Sector '}]",57,WDI Database Archives
24599,WP15163_4.9,"Mobile account, income, richest 60% (% ages 15+)",,Mobile account denotes the percentage of respo...,"Demirguc-Kunt et al., 2015, Global Financial I...","[{'id': '7', 'value': 'Financial Sector '}]",57,WDI Database Archives
24600,wpremia_F,Wage Premia for Females (the ratio of skilled ...,,,,[],80,Gender Disaggregated Labor Database (GDLD)
24601,wpremia_M,Wage Premia for Males (the ratio of skilled m...,,,,[{}],80,Gender Disaggregated Labor Database (GDLD)

In [127]:
indicators[indicators['name'] == 'Public Expenditure on Education']

Empty DataFrame
Columns: [id, name, unit, sourceNote, sourceOrganization, topics, source.id, source.value]
Index: []

In [114]:
id_values = pd.json_normalize(indicators.explode('topics')['topics'])
id_values

        id              value
0       11           Poverty
1       11           Poverty
2       11           Poverty
3       11           Poverty
4       11           Poverty
...    ...                ...
25333   17             Gender
25334    7  Financial Sector
25335    7  Financial Sector
25336  NaN                NaN
25337  NaN                NaN

[25338 rows x 2 columns]

In [116]:
id_values[id_values['value'] == "% GDP"]

Empty DataFrame
Columns: [id, value]
Index: []